dist: trusty
language: bash

before_script:
  - shellcheck -x ci/errata.sh

script:
  - echo "nop"
  # - bash ci/errata.sh pre docs/src docs/content

after_success:
  - bash docs/build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/public
  on:
    branch: master
