dist: trusty
language: bash

script:
  - shellcheck -x ci/errata.sh

after_success:
  - bash docs/build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/public
  on:
    branch: master
